### ISSUE TITLE
[FEATURE] 모바일 웹 기본 디자인 틀 설계

### ISSUE THREAD

**Issue by dilkusha27** [rolling-paper-toy/front-end#2]
## #️⃣ 요청 유형

> 해당되는 항목을 선택해주세요.
- [x] 새로운 기능 추가
- [ ] 기존 기능 개선
- [ ] 성능 개선

## #️⃣ 어떤 기능인가요?

> [FEATURE] 

## #️⃣ 이 기능이 필요한 이유는 무엇인가요?

> 백엔드의 로그인 로직과의 연결을 위해 필요 

## #️⃣ 구현 방안 (선택)

> 이 기능을 어떻게 구현할 수 있을지에 대한 아이디어를 간단히 설명해주세요.

## #️⃣ 작업 상세 내용

- [ ] 
- [ ] 

## 📎 참고할만한 자료 (선택)

> 관련 문서, 스크린샷, 또는 예시 등이 있다면 여기에 첨부해주세요.

**Comment by Soo186** [comment]
<img width="767" alt="스크린샷 2024-10-01 오후 2 03 35" src="https://github.com/user-attachments/assets/5e3aed7a-ddd1-420c-aac2-363312016c51">

@dilkusha27  @pangwoo96  @HIITMEMARIO  피그마 초기 완료 했습니다!
